### ISSUE TITLE
Feature request: Return to home

### ISSUE THREAD

**Issue by blakedietz** [nornagon/saxi#25]
Would it be possible to have a return to home function?

**Comment by nornagon** [comment]
Hm, I'm not sure I understand your use case. "Cancel" disengages the motors, which lets you just push the robot back to (0,0). Further, if you move the head by hand at all then a "Return Home" button could very easily run into the end of the axis.

Could you explain a little more about what you're envisioning here & what need this would address?

**Comment by blakedietz** [comment]
Actually, let's close this issue. I'll reopen if I end up changing my mind.

I misunderstood and thought you would be able to add a return to home function for the plotter so if you cancel a print, instead of disengaging the plotter would return home.

**Comment by nornagon** [comment]
Hm, I think it might be better not to automatically return home when cancelling a plot. It could be that the user is cancelling the plot due to a pen issue (e.g. not clamped tightly enough), & cancelling the plot could end up dragging the pen across the paper.

I can imagine a "return home" feature being useful if you were using a point other than the physical minimum limit of the AxiDraw's travel.
